import { Deadline } from "@/models/Deadline";
import { ClientDoc } from "@/models/Client";

/**
 * Compliance deadline generation for a managed SME. These follow the
 * commonly-cited FBR calendar; exact statutory dates shift with SROs, so
 * the dates are conservative reminders, not a legal guarantee. Verify
 * against the current schedule for each client.
 */
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

type PlannedDeadline = {
  type: "sales_tax_return" | "withholding_statement" | "income_tax_return" | "atl_renewal";
  title: string;
  periodLabel: string;
  dueDate: Date;
  genKey: string;
};

export function planDeadlines(client: Pick<ClientDoc, "salesTaxRegistered" | "filingFrequency" | "category">, now = new Date()): PlannedDeadline[] {
  const out: PlannedDeadline[] = [];
  const y = now.getFullYear();
  const m = now.getMonth();

  // Sales tax return — monthly, due the 18th of the following month.
  if (client.salesTaxRegistered) {
    const periods = client.filingFrequency === "quarterly" ? [0, 3, 6] : [0, 1, 2, 3];
    for (const offset of periods) {
      const periodDate = new Date(y, m + offset, 1);
      const due = new Date(y, m + offset + 1, 18);
      const label = `${MONTHS[periodDate.getMonth()]} ${periodDate.getFullYear()}`;
      out.push({
        type: "sales_tax_return",
        title: `Sales tax return — ${label}`,
        periodLabel: label,
        dueDate: due,
        genKey: `sales_tax_return:${label}`,
      });
    }
  }

  // Withholding statement — monthly, due the 15th of the following month.
  {
    const periodDate = new Date(y, m, 1);
    const due = new Date(y, m + 1, 15);
    const label = `${MONTHS[m]} ${y}`;
    out.push({
      type: "withholding_statement",
      title: `Withholding statement — ${label}`,
      periodLabel: label,
      dueDate: due,
      genKey: `withholding_statement:${label}`,
    });
  }

  // Annual income tax return — companies 31 Dec, others 30 Sep.
  {
    const isCompany = client.category === "public_company" || client.category === "private_company";
    const due = isCompany ? new Date(y, 11, 31) : new Date(y, 8, 30);
    const dueYear = due < now ? y + 1 : y;
    const finalDue = isCompany ? new Date(dueYear, 11, 31) : new Date(dueYear, 8, 30);
    const label = `TY ${dueYear}`;
    out.push({
      type: "income_tax_return",
      title: `Income tax return — ${label}`,
      periodLabel: label,
      dueDate: finalDue,
      genKey: `income_tax_return:${label}`,
    });
  }

  // ATL renewal — Active Taxpayer List refreshes ~1 March annually.
  {
    const due = new Date(y, 2, 1);
    const dueYear = due < now ? y + 1 : y;
    const label = `${dueYear}`;
    out.push({
      type: "atl_renewal",
      title: `ATL renewal / filer status — ${label}`,
      periodLabel: label,
      dueDate: new Date(dueYear, 2, 1),
      genKey: `atl_renewal:${label}`,
    });
  }

  return out;
}

/** Upsert auto-generated deadlines for a client without duplicating them. */
export async function syncDeadlines(client: ClientDoc) {
  const planned = planDeadlines(client);
  await Promise.all(
    planned.map((p) =>
      Deadline.updateOne(
        { clientId: client._id, genKey: p.genKey },
        {
          $setOnInsert: {
            firmId: client.firmId,
            clientId: client._id,
            type: p.type,
            title: p.title,
            periodLabel: p.periodLabel,
            dueDate: p.dueDate,
            autoGenerated: true,
            genKey: p.genKey,
            status: "pending",
          },
        },
        { upsert: true }
      )
    )
  );
}
