import { NextRequest, NextResponse } from "next/server";
import { dbConnect } from "@/lib/db";
import { Deadline } from "@/models/Deadline";
import { Client } from "@/models/Client";
import { getSession, clientScope, canAccessClient, logAudit } from "@/lib/access";
import { syncDeadlines } from "@/lib/deadlines";

export async function GET(_req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const s = await getSession();
  if (!s) return NextResponse.json({ error: "Not signed in." }, { status: 401 });
  const { id } = await ctx.params;
  await dbConnect();
  if (!(await canAccessClient(s, id))) return NextResponse.json({ error: "Client not found." }, { status: 404 });
  const deadlines = await Deadline.find({ firmId: s.firmId, clientId: id }).sort({ dueDate: 1 }).populate("assignedTo", "name");
  return NextResponse.json({ deadlines });
}

/** Add a custom deadline, or (action: "regenerate") refresh auto deadlines. */
export async function POST(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const s = await getSession();
  if (!s) return NextResponse.json({ error: "Not signed in." }, { status: 401 });
  const { id } = await ctx.params;
  await dbConnect();
  const client = await Client.findOne({ ...clientScope(s), _id: id });
  if (!client) return NextResponse.json({ error: "Client not found." }, { status: 404 });

  const b = await req.json();
  if (b.action === "regenerate") {
    await syncDeadlines(client);
    return NextResponse.json({ ok: true });
  }
  if (!b.title || !b.dueDate)
    return NextResponse.json({ error: "Title and due date are required." }, { status: 400 });
  const deadline = await Deadline.create({
    firmId: s.firmId,
    clientId: id,
    type: "custom",
    title: b.title,
    dueDate: new Date(b.dueDate),
    status: "pending",
    autoGenerated: false,
  });
  await logAudit(s, "deadline.create", { clientId: id, detail: deadline.title });
  return NextResponse.json({ deadline }, { status: 201 });
}
