"use client";
import { useEffect, useState, useCallback } from "react";
import { useParams } from "next/navigation";
import { ErrorNote, Empty } from "@/components/ui";
import { Button } from "@/components/Button";

type Deadline = { _id: string; title: string; type: string; periodLabel: string; dueDate: string; status: string; autoGenerated: boolean };

function badge(d: Deadline) {
  const now = Date.now();
  const due = new Date(d.dueDate).getTime();
  if (d.status === "done") return <span className="stamp stamp-accepted">Done</span>;
  if (d.status === "snoozed") return <span className="stamp stamp-draft">Snoozed</span>;
  if (due < now) return <span className="stamp stamp-rejected">Overdue</span>;
  if (due < now + 3 * 864e5) return <span className="stamp text-[color:var(--color-gold)] border-[color:var(--color-gold)]">Due soon</span>;
  return <span className="stamp stamp-draft">Pending</span>;
}

export default function DeadlinesPage() {
  const { id } = useParams();
  const [deadlines, setDeadlines] = useState<Deadline[]>([]);
  const [title, setTitle] = useState("");
  const [dueDate, setDueDate] = useState("");
  const [error, setError] = useState("");

  const load = useCallback(() => fetch(`/api/clients/${id}/deadlines`).then((r) => r.json()).then((d) => setDeadlines(d.deadlines || [])), [id]);
  useEffect(() => { load(); }, [load]);

  async function patch(did: string, body: Record<string, unknown>) {
    await fetch(`/api/deadlines/${did}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    load();
  }
  async function addCustom() {
    setError("");
    const res = await fetch(`/api/clients/${id}/deadlines`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, dueDate }) });
    if (res.ok) { setTitle(""); setDueDate(""); load(); } else setError((await res.json()).error || "Could not add.");
  }
  async function regenerate() { await fetch(`/api/clients/${id}/deadlines`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "regenerate" }) }); load(); }

  return (
    <div>
      <div className="flex items-center justify-between mb-1">
        <h1 className="display text-2xl font-bold">Compliance calendar</h1>
        <Button variant="ghost" className="text-xs" onClick={regenerate} loadingText="Regenerating…">Regenerate auto-deadlines</Button>
      </div>
      <p className="text-[color:var(--color-ink-soft)] mb-6 text-sm">Auto-generated from this client&apos;s filing profile. Dates are reminders — verify against the current FBR schedule.</p>

      <div className="card overflow-x-auto">
        <table className="ledger w-full">
          <thead><tr><th>Due</th><th>Obligation</th><th>Status</th><th></th></tr></thead>
          <tbody>
            {deadlines.map((d) => (
              <tr key={d._id}>
                <td className="mono whitespace-nowrap">{new Date(d.dueDate).toLocaleDateString("en-PK", { day: "numeric", month: "short", year: "numeric" })}</td>
                <td>{d.title}{!d.autoGenerated && <span className="mono text-[0.6rem] uppercase ml-2 text-[color:var(--color-ink-mute)]">custom</span>}</td>
                <td>{badge(d)}</td>
                <td className="text-right whitespace-nowrap space-x-2">
                  {d.status !== "done"
                    ? <Button variant="plain" className="text-xs text-[color:var(--color-pine)]" onClick={() => patch(d._id, { status: "done" })} loadingText="Saving…">Mark done</Button>
                    : <Button variant="plain" className="text-xs text-[color:var(--color-ink-soft)]" onClick={() => patch(d._id, { status: "pending" })} loadingText="Saving…">Reopen</Button>}
                  {d.status === "pending" && <Button variant="plain" className="text-xs text-[color:var(--color-ink-soft)]" onClick={() => patch(d._id, { status: "snoozed", snoozedUntil: new Date(Date.now() + 7 * 864e5) })} loadingText="Saving…">Snooze 7d</Button>}
                </td>
              </tr>
            ))}
            {deadlines.length === 0 && <Empty colSpan={4}>No deadlines. Use “Regenerate” to build the calendar.</Empty>}
          </tbody>
        </table>
      </div>

      <div className="card p-6 mt-4 grid sm:grid-cols-[1fr_auto_auto] gap-4 items-end">
        <div><label className="label">Add a custom deadline</label><input className="field" placeholder="e.g. Reply to FBR notice №123" value={title} onChange={(e) => setTitle(e.target.value)} /></div>
        <div><label className="label">Due date</label><input className="field mono" type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></div>
        <Button onClick={addCustom} disabled={!title || !dueDate} loadingText="Adding…">Add</Button>
      </div>
      <div className="mt-3"><ErrorNote msg={error} /></div>
    </div>
  );
}
