import mongoose, { Schema, InferSchemaType } from "mongoose";

/**
 * A compliance deadline for a managed SME. Most are auto-generated from
 * the SME's category/filing frequency; some can be added manually.
 */
const DeadlineSchema = new Schema(
  {
    firmId: { type: Schema.Types.ObjectId, ref: "Firm", required: true, index: true },
    clientId: { type: Schema.Types.ObjectId, ref: "Client", required: true, index: true },
    type: {
      type: String,
      enum: ["sales_tax_return", "withholding_statement", "income_tax_return", "atl_renewal", "custom"],
      default: "custom",
    },
    title: { type: String, required: true },
    periodLabel: { type: String, default: "" },
    dueDate: { type: Date, required: true, index: true },
    status: { type: String, enum: ["pending", "done", "snoozed"], default: "pending", index: true },
    snoozedUntil: { type: Date },
    assignedTo: { type: Schema.Types.ObjectId, ref: "User" },
    autoGenerated: { type: Boolean, default: false },
    // Idempotency key so re-generation doesn't duplicate the same deadline.
    genKey: { type: String, default: "", index: true },
  },
  { timestamps: true }
);

export type DeadlineDoc = InferSchemaType<typeof DeadlineSchema> & { _id: mongoose.Types.ObjectId };
export const Deadline = mongoose.models.Deadline || mongoose.model("Deadline", DeadlineSchema);
